# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data types of the variables list_ and array_list.

list_: This is a standard Python list that contains string elements. Its data type is list.
array_list: This is a NumPy array created from list_. The data type of array_list will be numpy.ndarray, and since the original list contains strings, the data type of the elements within the array will be str.

In [1]:
import numpy as np

# Create a list with corrected quotes
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data types
print("Data type of list_:", type(list_))  # Output: <class 'list'>
print("Data type of array_list:", type(array_list))  # Output: <class 'numpy.ndarray'>

# Print the data type of elements in array_list
print("Data type of elements in array_list:", array_list.dtype)  # Output: <U1 (string of Unicode characters)


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>
Data type of elements in array_list: <U1


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
import numpy as np

# Create a list with corrected quotes
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(f"{element}: {type(element)}")  # Output: <class 'str'>

# Print the data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(f"{element}: {type(element)}")  # Output: <class 'numpy.str_'>


Data types of elements in list_:
1: <class 'str'>
2: <class 'str'>
3: <class 'str'>
4: <class 'str'>
5: <class 'str'>

Data types of elements in array_list:
1: <class 'numpy.str_'>
2: <class 'numpy.str_'>
3: <class 'numpy.str_'>
4: <class 'numpy.str_'>
5: <class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [3]:
import numpy as np

# Create a list with corrected quotes
list_ = ['1', '2', '3', '4', '5']
# Create a NumPy array with dtype set to int
array_list = np.array(object=list_, dtype=int)

# Print the array
print("Array List with dtype int:", array_list)

# Print the data type of the array
print("Data type of array_list:", array_list.dtype)

# Print the data type of each element in the array
print("Data types of elements in array_list:")
for element in array_list:
    print(f"{element}: {type(element)}")


Array List with dtype int: [1 2 3 4 5]
Data type of array_list: int64
Data types of elements in array_list:
1: <class 'numpy.int64'>
2: <class 'numpy.int64'>
3: <class 'numpy.int64'>
4: <class 'numpy.int64'>
5: <class 'numpy.int64'>


# Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [4]:
import numpy as np

# Assuming num_array is similar to the previous example where array_list was created with integers
list_ = ['1', '2', '3', '4', '5']
num_array = np.array(object=list_, dtype=int)

# (i) Find the shape of num_array
shape_of_num_array = num_array.shape

# (ii) Find the size of num_array
size_of_num_array = num_array.size

# Print the results
print("Shape of num_array:", shape_of_num_array)  # Output: (5,)
print("Size of num_array:", size_of_num_array)    # Output: 5


Shape of num_array: (5,)
Size of num_array: 5


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [5]:
import numpy as np

# Create a 3x3 array filled with zeros
zero_matrix = np.zeros((3, 3))

# Print the resulting matrix
print("3x3 Matrix of Zeros:")
print(zero_matrix)


3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [6]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Alternatively, you can use np.identity(5)
# identity_matrix = np.identity(5)

# Print the resulting identity matrix
print("5x5 Identity Matrix:")
print(identity_matrix)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
